import { createElement, type ReactElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";

import {
  DevelopmentDemonstrationLabel,
  EstimatedCostLabel,
  OutboxEffectLabel,
  RecordingLabel,
  ReplayLabel,
  SimulatedOutboxLabel,
  SyntheticDataLabel,
  TestDoubleLabel,
  TestEvidenceLabel,
  VerdictSourceLabel,
} from ".";

const render = (element: ReactElement) => renderToStaticMarkup(element);

// The rendered text is what a reader sees: each label's mark must be present when the server data
// marks the thing, and absent (an empty render) when it does not.
describe("the label components", () => {
  it("shows the simulated outbox with its explanation by default", () => {
    const html = render(createElement(SimulatedOutboxLabel));
    expect(html).toContain('data-label="simulated_outbox"');
    expect(html).toContain("Simulated outbox");
    expect(html).toContain("a database record, no email is sent");
  });

  it("labels an outbox effect and only that effect", () => {
    expect(render(createElement(OutboxEffectLabel, { effect: "outbox_message_queued" }))).toContain(
      "Simulated outbox",
    );
    for (const effect of ["none", "read", "report_created", null, undefined]) {
      expect(render(createElement(OutboxEffectLabel, { effect }))).toBe("");
    }
  });

  it("labels a replay with its fixture id and a model proposal with nothing", () => {
    const html = render(
      createElement(ReplayLabel, {
        replaySource: "labelled_replay:hostile_note_redirect_record_v1",
      }),
    );
    expect(html).toContain('data-label="labelled_replay"');
    expect(html).toContain("Labelled replay");
    expect(html).toContain("hostile_note_redirect_record_v1");
    expect(html).toContain("scripted proposal, not generated by the model");
    expect(render(createElement(ReplayLabel, { replaySource: null }))).toBe("");
  });

  it("labels a verdict live or fixture and a deterministic control with nothing", () => {
    expect(render(createElement(VerdictSourceLabel, { verdictSource: "live" }))).toContain(
      "Live model",
    );
    expect(render(createElement(VerdictSourceLabel, { verdictSource: "fixture" }))).toContain(
      "Fixture verdict",
    );
    expect(render(createElement(VerdictSourceLabel, { verdictSource: null }))).toBe("");
  });

  it("labels the seeded operator and no other user", () => {
    expect(
      render(createElement(DevelopmentDemonstrationLabel, { email: "demo-operator@example.com" })),
    ).toContain("Development demonstration");
    expect(render(createElement(DevelopmentDemonstrationLabel, { email: "a@example.com" }))).toBe(
      "",
    );
  });

  it("labels an estimate with its rule, an unresolved reservation as uncertain, and a bare figure not at all", () => {
    expect(render(createElement(EstimatedCostLabel, { pricingRule: "local-model-v1" }))).toContain(
      "local-model-v1",
    );
    expect(render(createElement(EstimatedCostLabel, { unresolved: true }))).toContain("Uncertain");
    expect(render(createElement(EstimatedCostLabel, {}))).toBe("");
  });

  it("renders the other fixed labels and the recording label", () => {
    expect(render(createElement(TestDoubleLabel))).toContain("scripted, not the live model");
    expect(render(createElement(TestEvidenceLabel))).toContain(
      "a test run, not a live demonstration",
    );
    expect(render(createElement(SyntheticDataLabel))).toContain("Synthetic records");
    expect(render(createElement(RecordingLabel, { buildId: "6bbaac1" }))).toContain("Recording");
    expect(render(createElement(RecordingLabel, { buildId: null }))).toBe("");
  });

  it("puts the full sentence in the badge title and escapes a mark from the server", () => {
    const html = render(
      createElement(ReplayLabel, { replaySource: 'labelled_replay:<script>alert("x")</script>' }),
    );
    expect(html).not.toContain("<script>");
    expect(html).toContain("&lt;script&gt;");
  });
});
