import type { MigrationInterface, QueryRunner } from "typeorm";

// DRAFT (SH-26), pending the Go implementer and the lead. The lead assigned this draft to the
// infrastructure role on 2026-10-03. It builds on migrations that are drafts themselves: the
// runtime and demo drafts on feat/35-fixtures-and-tests (SH-16, SH-17, SH-24, SH-27, SH-44) and
// the control catalog on feat/fd-catalog-and-tests (API-31). It sorts after all of them and fails
// if one of their tables is missing.
//
// Decision 2: explicit, narrow privileges per service; the Go executor commits effects, lineage
// and completion on one connection, so the gateway is one role.
//
// - Roles are cluster-wide, so they are created only if missing. They are created NOLOGIN and
//   without a password: until a password is set from .env (follow-up below) nobody can log in as
//   them. Running this migration needs CREATEROLE (the image's POSTGRES_USER is a superuser).
// - Grants are explicit per table, with no default privileges: every later migration that adds a
//   table must grant on it. No role gets DELETE, TRUNCATE or DDL; the migration user stays the
//   owner of every object, and the seed and reset commands run as that user.
// - Where a draft trigger already freezes rows, the grant matches it (no UPDATE).
//
// Not granted yet, because the tables do not exist or the decision is open:
// - gateway read on the app task, policy and revocation records and on the identity records
//   behind operator and reviewer authority (decisions 4 and 7, SH-03, SH-38);
// - API read on runtime (`read path`), on form-option records (`form options`) and on the stored
//   report (`stored report read`);
// - lineage tables (`report storage`); UPDATE of a report title (`rename operation`).
//
// Follow-up, not wired here (proposal): POSTGRES_API_PASSWORD and POSTGRES_GATEWAY_PASSWORD,
// generated by `pnpm run setup` (scripts/lib/generated-secrets.mjs, which also puts them in the
// smoke leak checks), set by a root script such as `pnpm db:roles:password` running
// ALTER ROLE ... WITH LOGIN PASSWORD after the migrations, and read by each service's own
// connection settings. Role names are fixed here, never configurable.
const API_ROLE = "task_passport_api";
const GATEWAY_ROLE = "task_passport_gateway";

// Privileges per table: [schema, table, privileges].
const API_GRANTS: Array<[string, string, string]> = [
  // Imported revisions are immutable (draft trigger); the pointer moves on activation.
  ["app", "control_catalog_revisions", "SELECT, INSERT"],
  ["app", "signature_feed_revisions", "SELECT, INSERT"],
  ["app", "control_catalog_pointer", "SELECT, INSERT, UPDATE"],
];

const GATEWAY_GRANTS: Array<[string, string, string]> = [
  // Go reads the active catalog before each evaluation; NestJS alone activates revisions.
  ["app", "control_catalog_revisions", "SELECT"],
  ["app", "signature_feed_revisions", "SELECT"],
  ["app", "control_catalog_pointer", "SELECT"],
  // Immutable or append-only records.
  ["runtime", "passports", "SELECT, INSERT"],
  ["runtime", "audit_events", "SELECT, INSERT"],
  ["runtime", "control_assessments", "SELECT, INSERT"],
  ["runtime", "timing_records", "SELECT, INSERT"],
  // State that Go advances: run and job state, leases, settlement, the single approval consumption.
  ["runtime", "runs", "SELECT, INSERT, UPDATE"],
  ["runtime", "actions", "SELECT, INSERT, UPDATE"],
  ["runtime", "jobs", "SELECT, INSERT, UPDATE"],
  ["runtime", "model_calls", "SELECT, INSERT, UPDATE"],
  ["runtime", "execution_attempts", "SELECT, INSERT, UPDATE"],
  ["runtime", "approvals", "SELECT, INSERT, UPDATE"],
  ["runtime", "budget_reservations", "SELECT, INSERT, UPDATE"],
  // The GO-06 token ledger (AddModelTokenBudgets1791043000000), the one model-token authority:
  // Go reserves, settles and pauses balances. runtime.model_usage was removed in the alignment.
  ["runtime", "model_token_budgets", "SELECT, INSERT, UPDATE"],
  ["runtime", "model_token_reservations", "SELECT, INSERT, UPDATE"],
  // The tool adapters: read_invoice and read_vendor read; create_report and queue_report insert
  // immutable rows.
  ["demo", "vendors", "SELECT"],
  ["demo", "invoices", "SELECT"],
  ["demo", "reports", "SELECT, INSERT"],
  ["demo", "outbox_messages", "SELECT, INSERT"],
];

export class CreateServiceRoles1791050000000 implements MigrationInterface {
  name = "CreateServiceRoles1791050000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const roleName of [API_ROLE, GATEWAY_ROLE]) {
      await queryRunner.query(
        `DO $$ BEGIN
          IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${roleName}') THEN
            CREATE ROLE "${roleName}" NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
          END IF;
        END $$`,
      );
    }

    await this.grantAll(queryRunner, API_ROLE, API_GRANTS);
    await this.grantAll(queryRunner, GATEWAY_ROLE, GATEWAY_GRANTS);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // DROP OWNED revokes the role's privileges in this database (it owns nothing). DROP ROLE then
    // fails while a service is still connected as the role, or if another database granted it.
    for (const roleName of [GATEWAY_ROLE, API_ROLE]) {
      await queryRunner.query(`DROP OWNED BY "${roleName}"`);
      await queryRunner.query(`DROP ROLE "${roleName}"`);
    }
  }

  private async grantAll(
    queryRunner: QueryRunner,
    roleName: string,
    grants: Array<[string, string, string]>,
  ): Promise<void> {
    const schemaNames = [...new Set(grants.map(([schemaName]) => schemaName))];
    for (const schemaName of schemaNames) {
      await queryRunner.query(`GRANT USAGE ON SCHEMA "${schemaName}" TO "${roleName}"`);
    }
    for (const [schemaName, tableName, privileges] of grants) {
      await queryRunner.query(
        `GRANT ${privileges} ON "${schemaName}"."${tableName}" TO "${roleName}"`,
      );
    }
  }
}
