import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import type { SafeEvent } from "@workspace/contracts";
import exportDeniedFixture from "@workspace/contracts/fixtures/safe-event.export-denied.json";
import admissionRejectedFixture from "@workspace/contracts/fixtures/safe-event.admission-rejected.json";
import { ExportDenial, isExportDenial } from "./export-denial";

const exportDenied = exportDeniedFixture as SafeEvent;
const admissionRejected = admissionRejectedFixture as SafeEvent;

function render(event: SafeEvent): string {
  return renderToStaticMarkup(createElement(ExportDenial, { event }));
}

describe("ExportDenial", () => {
  it("explains the rule, the permitted recipient and the vendor continuation", () => {
    const html = render(exportDenied);
    expect(html).toContain("Export denied: the report inherits an Internal only restriction");
    expect(html).toContain("inherits it");
    expect(html).toContain("The recipient was permitted.");
    expect(html).toContain("vendor_reconciliation_v1");
    expect(html).toContain("approved database fields only");
    expect(html).toContain(exportDenied.maskedSummary.safeMessage as string);
  });

  it("links to the restricted report when the event names it", () => {
    const html = render(exportDenied);
    expect(html).toContain(
      `href="/runs/${exportDenied.runId}/reports/${exportDenied.maskedSummary.reportId}"`,
    );
  });

  it("is a denial and never an approval request: no action to take", () => {
    const html = render(exportDenied);
    expect(html).toContain("not an approval request");
    expect(html).not.toContain("<button");
    expect(html).not.toContain("Approve");
    expect(html).not.toContain("Reject");
  });

  it("explains an event that does not name the report, without a link or invented fields", () => {
    // The gate's real event carries the alternative and the message but no report id or template.
    const gateEvent = {
      ...exportDenied,
      maskedSummary: {
        ...exportDenied.maskedSummary,
        reportId: null,
        template: null,
        classification: null,
      },
    } as SafeEvent;
    const html = render(gateEvent);
    expect(html).toContain("vendor_reconciliation_v1");
    expect(html).not.toContain("View the restricted report");
    expect(html).not.toContain("internal_investigation_v1");
  });

  it("says plainly when no alternative was offered", () => {
    const html = render({
      ...exportDenied,
      maskedSummary: { ...exportDenied.maskedSummary, alternativeTemplate: null },
    } as SafeEvent);
    expect(html).toContain("No alternative was offered");
    expect(html).not.toContain("vendor_reconciliation_v1");
  });

  it("labels an export denial that came from a replay", () => {
    const html = render({
      ...exportDenied,
      maskedSummary: {
        ...exportDenied.maskedSummary,
        replaySource: "hostile_note_internal_disclosure_v1",
      },
    } as SafeEvent);
    expect(html).toContain("Replay: scripted proposal, not generated by the model");
    expect(html).toContain("hostile_note_internal_disclosure_v1");
  });

  it("renders nothing for any other event or reason", () => {
    expect(isExportDenial(exportDenied)).toBe(true);
    expect(isExportDenial(admissionRejected)).toBe(false);
    expect(render(admissionRejected)).toBe("");
    expect(render({ ...exportDenied, reasonCode: "destination_not_allowed" } as SafeEvent)).toBe(
      "",
    );
    expect(render({ ...exportDenied, eventType: "action.denied" } as SafeEvent)).toBe("");
  });
});
