// The truthful labels (WEB-13), in one place. The wording is the demonstration specification's label
// table (docs/product/storyboard.md, "Labels", X-16): a simulated outbox is a real prototype effect but
// not evidence of delivery, a replay is a scripted proposal, a fixture verdict says nothing about
// detection quality, the seeded operator is a development demonstration.
//
// Every label is derived from data the server sends (an action's `replaySource`, a control's
// `verdictSource`, an event's `effect`), never guessed by a page: the functions below return null when
// the data carries no mark, so an unmarked thing carries no label and a marked one always does.

export type LabelTone =
  | "simulation"
  | "replay"
  | "fixture"
  | "live"
  | "demonstration"
  | "estimate"
  | "synthetic"
  | "evidence";

export interface LabelText {
  /** Stable id for tests and styling hooks; never shown. */
  id: string;
  /** The compact badge text. */
  short: string;
  /** The full sentence the specification fixes. */
  full: string;
  tone: LabelTone;
}

export const LABELS = {
  simulatedOutbox: {
    id: "simulated_outbox",
    short: "Simulated outbox",
    full: "Simulated outbox: a database record, no email is sent",
    tone: "simulation",
  },
  replay: {
    id: "labelled_replay",
    short: "Labelled replay",
    full: "Replay: scripted proposal, not generated by the model",
    tone: "replay",
  },
  fixtureVerdict: {
    id: "fixture_verdict",
    short: "Fixture verdict",
    full: "Fixture verdict: tests handling, not detection quality",
    tone: "fixture",
  },
  liveVerdict: {
    id: "live_verdict",
    short: "Live model",
    full: "Live model verdict: one observation of the local model, not a detection rate",
    tone: "live",
  },
  testDouble: {
    id: "test_double",
    short: "Test double",
    full: "Labelled test double: scripted, not the live model",
    tone: "fixture",
  },
  testEvidence: {
    id: "test_evidence",
    short: "Test evidence",
    full: "Test evidence: a test run, not a live demonstration",
    tone: "evidence",
  },
  developmentDemonstration: {
    id: "development_demonstration",
    short: "Development demonstration",
    full: "Development Demonstration: a seeded local operator, not a production identity",
    tone: "demonstration",
  },
  syntheticData: {
    id: "synthetic_data",
    short: "Synthetic records",
    full: "Synthetic records: no real invoice, vendor, customer or bank data",
    tone: "synthetic",
  },
} as const satisfies Record<string, LabelText>;

/** The part of the full sentence after the compact text, for a view that shows both. */
export function labelDetail(label: LabelText): string {
  const separator = `${label.short}: `;
  return label.full.startsWith(separator) ? label.full.slice(separator.length) : label.full;
}

/** The prefix of an action's `replaySource` for a labelled replay (GO-36). */
const REPLAY_SOURCE_PREFIX = "labelled_replay:";

export interface ReplayLabel {
  label: LabelText;
  /** The replayed fixture's id, or null when the mark does not follow the labelled_replay:<id> form. */
  fixtureId: string | null;
}

/**
 * The label of a replayed proposal, from the action's (or event's) `replaySource`. null, undefined
 * and an empty string mean "a model proposal": no label. Any other value is a replay mark, so a mark
 * in an unexpected form still shows the label rather than hiding it.
 */
export function replayLabel(replaySource: string | null | undefined): ReplayLabel | null {
  if (replaySource === null || replaySource === undefined || replaySource === "") return null;
  if (replaySource.startsWith(REPLAY_SOURCE_PREFIX)) {
    const fixtureId = replaySource.slice(REPLAY_SOURCE_PREFIX.length);
    return { label: LABELS.replay, fixtureId: fixtureId === "" ? null : fixtureId };
  }
  return { label: LABELS.replay, fixtureId: null };
}

/**
 * The label of a semantic verdict, from a control assessment's `verdictSource`. "live" is a real local
 * model verdict and "fixture" a scripted one; null (a deterministic control, or a semantic check that
 * made no call) and anything unexpected carry no verdict label, so nothing is ever called live by
 * default.
 */
export function verdictSourceLabel(verdictSource: string | null | undefined): LabelText | null {
  if (verdictSource === "live") return LABELS.liveVerdict;
  if (verdictSource === "fixture") return LABELS.fixtureVerdict;
  return null;
}

/** The simulated-outbox label for an event whose `effect` is a queued outbox message, else null. */
export function outboxEffectLabel(effect: string | null | undefined): LabelText | null {
  return effect === "outbox_message_queued" ? LABELS.simulatedOutbox : null;
}

/**
 * The seeded operator's email (apps/api/src/auth/demo-operator-seed.ts). The session's `/me` carries
 * no flag for a development identity, so the label is derived from this seeded identity; a server
 * field would be better and is an open request.
 */
export const DEVELOPMENT_DEMONSTRATION_OPERATOR_EMAIL = "demo-operator@example.com";

export function isDevelopmentDemonstrationOperator(email: string | null | undefined): boolean {
  return (
    typeof email === "string" &&
    email.trim().toLowerCase() === DEVELOPMENT_DEMONSTRATION_OPERATOR_EMAIL
  );
}

export function developmentDemonstrationLabel(email: string | null | undefined): LabelText | null {
  return isDevelopmentDemonstrationOperator(email) ? LABELS.developmentDemonstration : null;
}

export interface EstimatedCost {
  /** The documented, versioned pricing rule behind an estimate; absent when there is none. */
  pricingRule?: string | null;
  /** True while a reservation has no settled usage: the amount is uncertain, never shown as zero. */
  unresolved?: boolean;
}

/**
 * The label of a cost figure: "Estimated" with its pricing rule, or "uncertain" for an unresolved
 * reservation. null means there is nothing honest to label, so the figure should not be shown (the
 * specification: "Estimated, with the pricing rule, or not shown").
 */
export function estimatedCostLabel(cost: EstimatedCost): LabelText | null {
  if (cost.unresolved === true) {
    return {
      id: "uncertain_cost",
      short: "Uncertain",
      full: "Uncertain: an unresolved reservation, not a measured amount and not zero",
      tone: "estimate",
    };
  }
  const rule = cost.pricingRule?.trim();
  if (rule === undefined || rule === "") return null;
  return {
    id: "estimated_cost",
    short: "Estimated",
    full: `Estimated: priced by the rule ${rule}, not a provider invoice`,
    tone: "estimate",
  };
}

/** "Recording from build <id>" for a recording or screenshot, or null without a build id. */
export function recordingLabel(buildId: string | null | undefined): LabelText | null {
  const id = buildId?.trim();
  if (id === undefined || id === "") return null;
  return {
    id: "recording",
    short: "Recording",
    full: `Recording from build ${id}`,
    tone: "evidence",
  };
}
