import { describe, expect, it } from "vitest";

import {
  developmentDemonstrationLabel,
  estimatedCostLabel,
  isDevelopmentDemonstrationOperator,
  LABELS,
  labelDetail,
  outboxEffectLabel,
  recordingLabel,
  replayLabel,
  verdictSourceLabel,
} from "./labels";

// The wording is the demonstration specification's label table (docs/product/storyboard.md, "Labels").
describe("the fixed wording", () => {
  it("matches the specification's sentences", () => {
    expect(LABELS.simulatedOutbox.full).toBe(
      "Simulated outbox: a database record, no email is sent",
    );
    expect(LABELS.replay.full).toBe("Replay: scripted proposal, not generated by the model");
    expect(LABELS.fixtureVerdict.full).toBe(
      "Fixture verdict: tests handling, not detection quality",
    );
    expect(LABELS.testDouble.full).toBe("Labelled test double: scripted, not the live model");
    expect(LABELS.testEvidence.full).toBe("Test evidence: a test run, not a live demonstration");
    expect(LABELS.developmentDemonstration.short).toBe("Development demonstration");
  });

  it("never states what the product does not do", () => {
    // A simulated outbox must not read as delivery, and a verdict label must not claim detection.
    expect(LABELS.simulatedOutbox.full).not.toMatch(/sent to|delivered/i);
    expect(LABELS.simulatedOutbox.full).toMatch(/no email is sent/);
    expect(LABELS.liveVerdict.full).toMatch(/not a detection rate/);
    expect(LABELS.fixtureVerdict.full).toMatch(/not detection quality/);
  });

  it("splits a sentence into its badge text and its explanation", () => {
    expect(labelDetail(LABELS.simulatedOutbox)).toBe("a database record, no email is sent");
    // A label whose sentence does not start with its badge text shows the whole sentence.
    expect(labelDetail(LABELS.replay)).toBe(LABELS.replay.full);
  });
});

describe("a replayed proposal", () => {
  it("always carries the label when the server marks it", () => {
    const replay = replayLabel("labelled_replay:hostile_note_internal_disclosure_v1");
    expect(replay?.label).toBe(LABELS.replay);
    expect(replay?.fixtureId).toBe("hostile_note_internal_disclosure_v1");
  });

  it("carries none without the mark", () => {
    expect(replayLabel(null)).toBeNull();
    expect(replayLabel(undefined)).toBeNull();
    expect(replayLabel("")).toBeNull();
  });

  it("still shows the label for a mark in an unexpected form, never hiding it", () => {
    expect(replayLabel("scripted")).toEqual({ label: LABELS.replay, fixtureId: null });
    expect(replayLabel("labelled_replay:")).toEqual({ label: LABELS.replay, fixtureId: null });
  });
});

describe("a semantic verdict", () => {
  it("is labelled live or fixture from the server's source, and nothing else", () => {
    expect(verdictSourceLabel("live")).toBe(LABELS.liveVerdict);
    expect(verdictSourceLabel("fixture")).toBe(LABELS.fixtureVerdict);
    expect(verdictSourceLabel(null)).toBeNull();
    expect(verdictSourceLabel(undefined)).toBeNull();
  });

  it("is never called live by default", () => {
    expect(verdictSourceLabel("something_new")).toBeNull();
    expect(verdictSourceLabel("")).toBeNull();
  });
});

describe("the outbox", () => {
  it("labels a queued outbox message as simulated", () => {
    expect(outboxEffectLabel("outbox_message_queued")).toBe(LABELS.simulatedOutbox);
  });

  it("labels no other effect", () => {
    for (const effect of ["none", "read", "report_created", null, undefined]) {
      expect(outboxEffectLabel(effect)).toBeNull();
    }
  });
});

describe("the development demonstration operator", () => {
  it("is recognized from the seeded identity", () => {
    expect(isDevelopmentDemonstrationOperator("demo-operator@example.com")).toBe(true);
    expect(isDevelopmentDemonstrationOperator("  Demo-Operator@Example.com ")).toBe(true);
    expect(developmentDemonstrationLabel("demo-operator@example.com")).toBe(
      LABELS.developmentDemonstration,
    );
  });

  it("is not claimed for any other user", () => {
    expect(isDevelopmentDemonstrationOperator("someone@example.com")).toBe(false);
    expect(isDevelopmentDemonstrationOperator(null)).toBe(false);
    expect(developmentDemonstrationLabel(undefined)).toBeNull();
  });
});

describe("a cost figure", () => {
  it("is labelled estimated with its pricing rule", () => {
    const label = estimatedCostLabel({ pricingRule: "local-model-v1" });
    expect(label?.short).toBe("Estimated");
    expect(label?.full).toContain("local-model-v1");
    expect(label?.full).toMatch(/not a provider invoice/);
  });

  it("is uncertain, not zero, while a reservation is unresolved", () => {
    const label = estimatedCostLabel({ unresolved: true, pricingRule: "local-model-v1" });
    expect(label?.short).toBe("Uncertain");
    expect(label?.full).toMatch(/not zero/);
  });

  it("has no label, so should not be shown, without a rule", () => {
    expect(estimatedCostLabel({})).toBeNull();
    expect(estimatedCostLabel({ pricingRule: "  " })).toBeNull();
    expect(estimatedCostLabel({ pricingRule: null })).toBeNull();
  });
});

describe("a recording", () => {
  it("names its build", () => {
    expect(recordingLabel("6bbaac1")?.full).toBe("Recording from build 6bbaac1");
  });

  it("has no label without a build id", () => {
    expect(recordingLabel(" ")).toBeNull();
    expect(recordingLabel(null)).toBeNull();
  });
});
